name: Stage CI/CD
on:
  push:
    branches:
      - 'stage'

  pull_request:
    branches:
      - 'stage'

env:
  CI: false

jobs:
  deploy:
    name: build docker image and push to docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: stage

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build && push
        id: build-push
        uses: docker/build-push-action@v3
        if: github.event_name == 'push'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: esatya/rahat-otp-server:stage2

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t myimage:${{ github.sha }} .
